export const REQUEST_TOURNAMENTS = 'REQUEST_TOURNAMENTS';
export const RECEIVE_TOURNAMENTS = 'RECEIVE_TOURNAMENTS';
export const RECEIVE_TOURNAMENTS_ERROR = 'RECEIVE_TOURNAMENTS_ERROR';

export const REQUEST_ADD_TOURNAMENT = 'REQUEST_ADD_TOURNAMENT';
export const RECEIVE_ADD_TOURNAMENT = 'RECEIVE_ADD_TOURNAMENT';
export const RECEIVE_ADD_TOURNAMENT_ERROR = 'RECEIVE_ADD_TOURNAMENT_ERROR';

export const REQUEST_ADD_DIVISION = 'REQUEST_ADD_DIVISION';
export const RECEIVE_ADD_DIVISION = 'RECEIVE_ADD_DIVISION';
export const RECEIVE_ADD_DIVISION_ERROR = 'RECEIVE_ADD_DIVISION_ERROR';