export const REQUEST_AGE_CATEGORIES = 'REQUEST_AGE_CATEGORIES';
export const RECEIVE_AGE_CATEGORIES = 'RECEIVE_AGE_CATEGORIES';
export const RECEIVE_AGE_CATEGORIES_ERROR = 'RECEIVE_AGE_CATEGORIES_ERROR';

export const REQUEST_EXPERIENCE_CATEGORIES = 'REQUEST_EXPERIENCE_CATEGORIES';
export const RECEIVE_EXPERIENCE_CATEGORIES = 'RECEIVE_EXPERIENCE_CATEGORIES';
export const RECEIVE_EXPERIENCE_CATEGORIES_ERROR = 'RECEIVE_EXPERIENCE_CATEGORIES_ERROR';

export const REQUEST_GENDER_CATEGORIES = 'REQUEST_GENDER_CATEGORIES';
export const RECEIVE_GENDER_CATEGORIES = 'RECEIVE_GENDER_CATEGORIES';
export const RECEIVE_GENDER_CATEGORIES_ERROR = 'RECEIVE_GENDER_CATEGORIES_ERROR';

export const REQUEST_WEIGHT_CATEGORIES = 'REQUEST_WEIGHT_CATEGORIES';
export const RECEIVE_WEIGHT_CATEGORIES = 'RECEIVE_WEIGHT_CATEGORIES';
export const RECEIVE_WEIGHT_CATEGORIES_ERROR = 'RECEIVE_WEIGHT_CATEGORIES_ERROR';

export const REQUEST_ADD_AGE_CATEGORY_GROUP = 'REQUEST_ADD_AGE_CATEGORY_GROUP';
export const RECEIVE_ADD_AGE_CATEGORY_GROUP = 'RECEIVE_ADD_AGE_CATEGORY_GROUP';
export const RECEIVE_ADD_AGE_CATEGORY_GROUP_ERROR = 'RECEIVE_ADD_AGE_CATEGORY_GROUP_ERROR';

export const REQUEST_ADD_EXPERIENCE_CATEGORY_GROUP = 'REQUEST_ADD_EXPERIENCE_CATEGORY_GROUP';
export const RECEIVE_ADD_EXPERIENCE_CATEGORY_GROUP = 'RECEIVE_ADD_EXPERIENCE_CATEGORY_GROUP';
export const RECEIVE_ADD_EXPERIENCE_CATEGORY_GROUP_ERROR = 'RECEIVE_ADD_EXPERIENCE_CATEGORY_GROUP_ERROR';

export const REQUEST_ADD_AGE_CATEGORY = 'REQUEST_ADD__CATEGORY';
export const RECEIVE_ADD_AGE_CATEGORY = 'RECEIVE_ADD_AGE_CATEGORY';
export const RECEIVE_ADD_AGE_CATEGORY_ERROR = 'RECEIVE_ADD_AGE_CATEGORY_ERROR';

export const REQUEST_ADD_EXPERIENCE_CATEGORY = 'REQUEST_ADD_EXPERIENCE_CATEGORY';
export const RECEIVE_ADD_EXPERIENCE_CATEGORY = 'RECEIVE_ADD_EXPERIENCE_CATEGORY';
export const RECEIVE_ADD_EXPERIENCE_CATEGORY_ERROR = 'RECEIVE_ADD_EXPERIENCE_CATEGORY_ERROR';

export const REQUEST_UPDATE_AGE_CATEGORY_GROUP = 'REQUEST_UPDATE_AGE_CATEGORY_GROUP';
export const RECEIVE_UPDATE_AGE_CATEGORY_GROUP = 'RECEIVE_UPDATE_AGE_CATEGORY_GROUP';
export const RECEIVE_UPDATE_AGE_CATEGORY_GROUP_ERROR = 'RECEIVE_UPDATE_AGE_CATEGORY_GROUP_ERROR';

export const REQUEST_UPDATE_EXPERIENCE_CATEGORY_GROUP = 'REQUEST_UPDATE_EXPERIENCE_CATEGORY_GROUP';
export const RECEIVE_UPDATE_EXPERIENCE_CATEGORY_GROUP = 'RECEIVE_UPDATE_EXPERIENCE_CATEGORY_GROUP';
export const RECEIVE_UPDATE_EXPERIENCE_CATEGORY_GROUP_ERROR = 'RECEIVE_UPDATE_EXPERIENCE_CATEGORY_GROUP_ERROR';

export const REQUEST_DELETE_AGE_CATEGORY_GROUP = 'REQUEST_DELETE_AGE_CATEGORY_GROUP';
export const RECEIVE_DELETE_AGE_CATEGORY_GROUP = 'RECEIVE_DELETE_AGE_CATEGORY_GROUP';
export const RECEIVE_DELETE_AGE_CATEGORY_GROUP_ERROR = 'RECEIVE_DELETE_AGE_CATEGORY_GROUP_ERROR';

export const REQUEST_DELETE_EXPERIENCE_CATEGORY_GROUP = 'REQUEST_DELETE_EXPERIENCE_CATEGORY_GROUP';
export const RECEIVE_DELETE_EXPERIENCE_CATEGORY_GROUP = 'RECEIVE_DELETE_EXPERIENCE_CATEGORY_GROUP';
export const RECEIVE_DELETE_EXPERIENCE_CATEGORY_GROUP_ERROR = 'RECEIVE_DELETE_EXPERIENCE_CATEGORY_GROUP_ERROR';

export const REQUEST_UPDATE_AGE_CATEGORY = 'REQUEST_UPDATE_AGE_CATEGORY';
export const RECEIVE_UPDATE_AGE_CATEGORY = 'RECEIVE_UPDATE_AGE_CATEGORY';
export const RECEIVE_UPDATE_AGE_CATEGORY_ERROR = 'RECEIVE_UPDATE_AGE_CATEGORY_ERROR';

export const REQUEST_UPDATE_EXPERIENCE_CATEGORY = 'REQUEST_UPDATE_EXPERIENCE_CATEGORY';
export const RECEIVE_UPDATE_EXPERIENCE_CATEGORY = 'RECEIVE_UPDATE_EXPERIENCE_CATEGORY';
export const RECEIVE_UPDATE_EXPERIENCE_CATEGORY_ERROR = 'RECEIVE_UPDATE_EXPERIENCE_CATEGORY_ERROR';

export const REQUEST_DELETE_AGE_CATEGORY = 'REQUEST_DELETE_AGE_CATEGORY';
export const RECEIVE_DELETE_AGE_CATEGORY = 'RECEIVE_DELETE_AGE_CATEGORY';
export const RECEIVE_DELETE_AGE_CATEGORY_ERROR = 'RECEIVE_DELETE_AGE_CATEGORY_ERROR';

export const REQUEST_DELETE_EXPERIENCE_CATEGORY = 'REQUEST_DELETE_EXPERIENCE_CATEGORY';
export const RECEIVE_DELETE_EXPERIENCE_CATEGORY = 'RECEIVE_DELETE_EXPERIENCE_CATEGORY';
export const RECEIVE_DELETE_EXPERIENCE_CATEGORY_ERROR = 'RECEIVE_DELETE_EXPERIENCE_CATEGORY_ERROR';
